#include <iostream>
#include <fstream>
#include <iomanip>
#include <vector>
#include <string>
#include <cmath>
#include "../fastkmeanspp.hpp"

struct CaseDef {
  std::string name;
  std::string file;   // relative to tests/ when executed
  int k;
  unsigned seed;
};

static long double fingerprint(const FastKMeansPP::Matrix& C) {
  // Deterministic "signature" of centers matrix (catches many changes).
  long double fp = 0.0L;
  for (int i = 0; i < C.rows(); ++i) {
    for (int j = 0; j < C.cols(); ++j) {
      fp += (long double)(i + 1) * (long double)(j + 1) * (long double)C(i, j);
    }
  }
  return fp;
}

int main() {
  // Run from tests/ directory (Makefile does that implicitly if you run `make` inside tests/)
  // Files should therefore be "data/....csv".

  std::vector<CaseDef> cases = {
    // 18 points, 2D (two blobs)
    {"gauss2d_k2_s0",  "data/gauss2d_3x3_per_cluster.csv", 2, 0},
    {"gauss2d_k4_s0",  "data/gauss2d_3x3_per_cluster.csv", 4, 0},
    {"gauss2d_k6_s1",  "data/gauss2d_3x3_per_cluster.csv", 6, 1},

    // 24 points, 3D (two blobs)
    {"gauss3d_k2_s0",  "data/gauss3d_4x3_per_cluster.csv", 2, 0},
    {"gauss3d_k4_s0",  "data/gauss3d_4x3_per_cluster.csv", 4, 0},
    {"gauss3d_k6_s1",  "data/gauss3d_4x3_per_cluster.csv", 6, 1},

    // 32 points, 2D (ring-ish)
    {"ring2d_k6_s0",   "data/ring2d_32.csv", 6, 0},
    {"ring2d_k10_s1",  "data/ring2d_32.csv", 10, 1},

    // 50 points, 2D (three blobs)
    {"mix2d_k3_s0",    "data/mix2d_50.csv", 3, 0},
    {"mix2d_k8_s0",    "data/mix2d_50.csv", 8, 0},
    {"mix2d_k10_s1",   "data/mix2d_50.csv", 10, 1},
  };

  // Open outputs
  std::ofstream json("golden.json");
  std::ofstream hdr("golden_generated.hpp");
  if (!json || !hdr) {
    std::cerr << "Error: could not open golden.json or golden_generated.hpp for writing.\n";
    return 1;
  }

  json << std::setprecision(17) << std::fixed;
  hdr  << std::setprecision(17) << std::fixed;

  // JSON header
  json << "{\n";
  json << "  \"version\": 1,\n";
  json << "  \"note\": \"Generated by tests/update_golden.cpp. Commit golden.json + golden_generated.hpp.\",\n";
  json << "  \"cases\": [\n";

  // C++ header
  hdr << "#pragma once\n";
  hdr << "// Auto-generated by update_golden.cpp. Commit this file.\n\n";
  hdr << "#include <cstddef>\n\n";
  hdr << "struct GoldenCase {\n";
  hdr << "  const char* name;\n";
  hdr << "  const char* file;\n";
  hdr << "  int k;\n";
  hdr << "  unsigned seed;\n";
  hdr << "  double score[3]; // [0]=Std [1]=TIE [2]=TIE+Norm\n";
  hdr << "  double fp[3];    // fingerprints\n";
  hdr << "};\n\n";
  hdr << "static const GoldenCase GOLDEN_CASES[] = {\n";

  // Generate results
  for (size_t ci = 0; ci < cases.size(); ++ci) {
    const auto& tc = cases[ci];

    double score[3] = {0,0,0};
    long double fp[3] = {0,0,0};

    for (int acc = 0; acc < 3; ++acc) {
      FastKMeansPP::Matrix centers;
      double s = FastKMeansPP::run_kmeanspp(tc.file, centers, tc.k, tc.seed, acc);
      score[acc] = s;
      fp[acc] = fingerprint(centers);
    }

    // JSON case
    json << "    {\n";
    json << "      \"name\": \"" << tc.name << "\",\n";
    json << "      \"file\": \"" << tc.file << "\",\n";
    json << "      \"k\": " << tc.k << ",\n";
    json << "      \"seed\": " << tc.seed << ",\n";
    json << "      \"results\": {\n";
    json << "        \"std\":     {\"score\": " << score[0] << ", \"fp\": " << (double)fp[0] << "},\n";
    json << "        \"tie\":     {\"score\": " << score[1] << ", \"fp\": " << (double)fp[1] << "},\n";
    json << "        \"tienorm\": {\"score\": " << score[2] << ", \"fp\": " << (double)fp[2] << "}\n";
    json << "      }\n";
    json << "    }" << (ci + 1 < cases.size() ? "," : "") << "\n";

    // Header case
    hdr << "  {\n";
    hdr << "    \"" << tc.name << "\", \"" << tc.file << "\", " << tc.k << ", " << tc.seed << ",\n";
    hdr << "    {" << score[0] << ", " << score[1] << ", " << score[2] << "},\n";
    hdr << "    {" << (double)fp[0] << ", " << (double)fp[1] << ", " << (double)fp[2] << "}\n";
    hdr << "  }" << (ci + 1 < cases.size() ? "," : "") << "\n";
  }

  json << "  ]\n";
  json << "}\n";

  hdr << "};\n";
  hdr << "static constexpr std::size_t GOLDEN_CASES_COUNT = sizeof(GOLDEN_CASES)/sizeof(GOLDEN_CASES[0]);\n";

  std::cout << "Generated golden.json and golden_generated.hpp with " << cases.size() << " cases.\n";
  std::cout << "Next: run `make test` and commit both generated files.\n";
  return 0;
}
